### ISSUE TITLE
CloudVision V3.20, how does Be My AI integration work?

### ISSUE THREAD

**Issue by amirsol81** [alekssamos/cloudvision#14]
Greetings @alekssamos
V3.20 of CloudVision provides support for Be My AI. It even offers a check box for it which is checked by default. So how does it work, or what does it need? My results with the updated add-on seem similar to the ones with the older release. So please kindly shed some light on it.

**Comment by alekssamos** [comment]
Hello. Yes, everything should work immediately after installation. I checked.

**Comment by amirsol81** [comment]
@alekssamos But I get the exact same results, with or without that check box checked. I mean regardless of the status of the check box, my image descriptions are the same, and as brief as those of the previous releases. What do you think might be wrong at my end?

**Comment by amirsol81** [comment]
@alekssamos Well, further analysis indicates that Be My AI works for some users, and doesn't work for others. A friend of mine and I worked on an example image. He gets longer and detailed Be My AI descriptions from the image, and I always get the old, shorter one regardless of the status of the check box in the Settings window. I'd be happy to help further test it.
