### ISSUE TITLE
Обновление украинского перевода

### ISSUE THREAD

**Issue by VovaMobile** [alekssamos/cloudvision#4]
Здравствуйте. Я опубликовал в виде pull request обновление перевода дополнения для NVDA на украинский язык, поскольку он содержыт некоторые ошибки. С того времени вышло уже два обновления, но обновленный перевод в дополнение не был включен. Включите его, пожалуйста, и скажите, почему он не был включен.

**Comment by alekssamos** [comment]
Почему-то Ваши файлы у меня были не в папке addon/locale/uk, а в корне. Теперь исправил. Странно.
